jobs:
  build:
    name: "AmneziaWG for GL-AXT1800"
    runs-on: ubuntu-latest
    env:
      GLINET_VERMAGIC: "57d388dbd346719758aae2131362f842"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v21.02.7
          fetch-depth: 0

      - name: Setup GL.iNet custom config
        run: |
          # Создаём кастомный feeds.conf
          cat > feeds.conf <<EOF
          src-git packages https://git.openwrt.org/feed/packages.git^9e2b97c
          src-git luci https://git.openwrt.org/project/luci.git^a8b1c78
          src-git routing https://git.openwrt.org/feed/routing.git^b5e4e1e
          src-git telephony https://git.openwrt.org/feed/telephony.git^f1a4d0d
          src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git
          EOF
          
          # Базовая конфигурация
          cat > .config <<EOF
          CONFIG_TARGET_ipq40xx=y
          CONFIG_TARGET_ipq40xx_generic=y
          CONFIG_PACKAGE_kmod-amneziawg=m
          CONFIG_PACKAGE_amneziawg-tools=y
          CONFIG_PACKAGE_luci-app-amneziawg=y
          EOF

          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
